### ISSUE TITLE
Tarefa 1 -  Desenhar 'Star Polygons'

### ISSUE THREAD

**Issue by Dnunes20** [Dnunes20/Grupo_4_PARI19#2]
@pedrocostaM  ficas de tratar de por a funcionar o 'STAR POLYGON'. Cumprimentos!

**Comment by migasneto199797** [comment]
I am on it !!

**Comment by pedrocostaM** [comment]
Terminado

![image](https://user-images.githubusercontent.com/58780713/70645402-d4154280-1c3c-11ea-94bf-f0ed916458d1.png)
